language: node_js
node_js:
- "10"
branches:
  only:
  - master
install:
- npm install
script:
- npm run build
- cd dist/docs
- echo "blog.cookapps.io" > CNAME
- git config --global user.name 'VuePressBot'
- git config --global user.email 'vuepressbot@cookapps.com'
- git init
- git add -A
- git commit -m 'deploy via travis'
- git push -f https://${__GITHUB_TOKEN__}@github.com/cookpi/cookpi.github.io.git master
notifications:
  email:
    on_success: never
    on_failure: always

